package gamecube

import (
	"bytes"
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"wiibridge/server/host-daemon/fat32virtual"
)

func TestLegacyEnrollmentWriteFailureKeepsHostStartupRecoverable(t *testing.T) {
	if os.Geteuid() == 0 {
		t.Skip("requires unprivileged permission enforcement")
	}
	sources, managed := t.TempDir(), t.TempDir()
	manager := libraryManager(t, managed, sources)
	manifest, err := manager.Build(context.Background(), libraryGames(t, sources))
	if err != nil {
		t.Fatal(err)
	}
	if manifest.Files[0].Identity.FilesystemID == "" {
		t.Skip("run on ext4 or ZFS for persistent filesystem integration")
	}
	manifest = historicalIdentityFixture(t, manifest, func(id *fat32virtual.Identity) { id.FilesystemID = "" })
	receipt := ValidationReceipt{Schema: validationReceiptSchema, ValidatorSchema: LibrarySchema, GenerationID: manifest.GenerationID, CatalogFingerprint: manifest.CatalogFingerprint, SourceIdentitySetHash: sourceIdentitySetHash(manifest), Completed: manifest.Created, Result: "validated"}
	if err = persistValidationReceipt(managed, manifest, receipt); err != nil {
		t.Fatal(err)
	}
	directory := filepath.Dir(manifest.LayoutPath)
	if err = os.Chmod(directory, 0500); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chmod(directory, 0700) })
	// Manager construction must succeed so a GameCube migration write failure
	// cannot abort the entire host and its independently healthy Wii library.
	reopened := libraryManager(t, managed, sources)
	if _, ready := reopened.ValidatedSummary(); ready || reopened.Progress().Validation != "blocked" {
		t.Fatal("failed enrollment left generation ready")
	}
	if err = manager.RecheckActive(); err == nil {
		t.Fatal("failed receipt persistence was ignored")
	}
	if _, ready := manager.ValidatedSummary(); ready {
		t.Fatal("failed recheck retained stale readiness")
	}
	if err = os.Chmod(directory, 0700); err != nil {
		t.Fatal(err)
	}
	if err = reopened.RecheckActive(); err != nil {
		t.Fatal("enrollment could not recover", err)
	}
	if _, ready := reopened.ValidatedSummary(); !ready {
		t.Fatal("successful enrollment did not restore readiness")
	}
}

// Publish a synthetic historical generation with a chosen identity format.
// All metadata is generated by the production layout builder; no payload is
// altered. This simulates persisted metadata from before a device renumbering.
func historicalIdentityFixture(t *testing.T, manifest LibraryManifest, change func(*fat32virtual.Identity)) LibraryManifest {
	t.Helper()
	files := append([]fat32virtual.File(nil), manifest.Files...)
	for i := range files {
		if !files[i].Writable {
			change(&files[i].Identity)
		}
	}
	layout, metadata, err := fat32virtual.Build(manifest.VolumeSize, "WIIBRIDGE", manifest.CatalogFingerprint, files)
	if err != nil {
		t.Fatal(err)
	}
	manifest.Files, manifest.MetadataHash, manifest.ExtentMapHash = layout.Files, layout.MetadataHash, layout.ExtentMapHash
	manifest.LayoutChecksum, manifest.SaveExtentHash = layout.LayoutChecksum, layout.SaveExtentHash
	data, err := json.MarshalIndent(layout, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	write := func(path string, data []byte) {
		t.Helper()
		if err := os.WriteFile(path, data, 0600); err != nil {
			t.Fatal(err)
		}
	}
	write(manifest.LayoutPath, append(data, '\n'))
	write(manifest.MetadataPath, metadata)
	checksums := map[string]string{"layout_sha256": hashBytes(data), "metadata_sha256": layout.MetadataHash, "extent_map_sha256": layout.ExtentMapHash, "save_extent_map_sha256": layout.SaveExtentHash, "layout_checksum": layout.LayoutChecksum}
	encoded, _ := json.Marshal(map[string]any{"schema": LibrarySchema, "checksums": checksums})
	write(filepath.Join(filepath.Dir(manifest.LayoutPath), "checksums.json"), encoded)
	encoded, _ = json.Marshal(manifest)
	write(filepath.Join(filepath.Dir(manifest.LayoutPath), "manifest.json"), encoded)
	return manifest
}

func TestGameCubeStableGenerationReopensAndReadsAfterDeviceRenumbering(t *testing.T) {
	sources, managed := t.TempDir(), t.TempDir()
	manager := libraryManager(t, managed, sources)
	manifest, err := manager.Build(context.Background(), libraryGames(t, sources))
	if err != nil {
		t.Fatal(err)
	}
	if manifest.Files[0].Identity.FilesystemID == "" {
		t.Skip("run on ext4 or ZFS for persistent filesystem integration")
	}
	manifest = historicalIdentityFixture(t, manifest, func(id *fat32virtual.Identity) { id.Device++ })
	if err = writeValidationReceipt(managed, manifest); err != nil {
		t.Fatal(err)
	}
	receiptBefore, _ := os.ReadFile(validationReceiptPath(manifest))
	reopened := libraryManager(t, managed, sources)
	if _, ready := reopened.ValidatedSummary(); !ready {
		t.Fatalf("generation unnecessarily blocked: %#v", reopened.Progress())
	}
	active, err := reopened.Active()
	if err != nil || active.GenerationID != manifest.GenerationID {
		t.Fatal("generation was not reused", err)
	}
	backend, err := OpenLibraryBackend(managed, active)
	if err != nil {
		t.Fatal(err)
	}
	defer backend.Close()
	for _, file := range active.Files {
		actual := make([]byte, 512)
		if _, err = backend.ReadAt(actual, file.VirtualOffset); err != nil {
			t.Fatal("remounted file read rejected", err)
		}
		source, _ := os.Open(file.SourcePath)
		expected := make([]byte, 512)
		_, err = source.ReadAt(expected, file.SourceOffset)
		_ = source.Close()
		if err != nil || !bytes.Equal(actual, expected) {
			t.Fatal("payload mismatch", err)
		}
	}
	receiptAfter, _ := os.ReadFile(validationReceiptPath(manifest))
	if !bytes.Equal(receiptBefore, receiptAfter) {
		t.Fatal("unchanged sources forced revalidation")
	}
	file := active.Files[0]
	if err = os.Rename(file.SourcePath, file.SourcePath+".original"); err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(file.SourcePath + ".original")
	if err = os.WriteFile(file.SourcePath, data, 0600); err != nil {
		t.Fatal(err)
	}
	if _, err = backend.ReadAt(make([]byte, 512), file.VirtualOffset); err == nil {
		t.Fatal("runtime file replacement accepted")
	}
	if _, err = reopened.Active(); err == nil {
		t.Fatal("changed source retained activation")
	}
}

func TestLegacyGameCubeReceiptMigrationKeepsImmutableGeneration(t *testing.T) {
	sources, managed := t.TempDir(), t.TempDir()
	manager := libraryManager(t, managed, sources)
	manifest, err := manager.Build(context.Background(), libraryGames(t, sources))
	if err != nil {
		t.Fatal(err)
	}
	if manifest.Files[0].Identity.FilesystemID == "" {
		t.Skip("run on ext4 or ZFS for persistent filesystem integration")
	}
	manifest = historicalIdentityFixture(t, manifest, func(id *fat32virtual.Identity) { id.FilesystemID = "" })
	// A genuine legacy receipt has no filesystem enrollment.
	receipt := ValidationReceipt{Schema: validationReceiptSchema, ValidatorSchema: LibrarySchema, GenerationID: manifest.GenerationID, CatalogFingerprint: manifest.CatalogFingerprint, SourceIdentitySetHash: sourceIdentitySetHash(manifest), Completed: manifest.Created, Result: "validated"}
	if err = persistValidationReceipt(managed, manifest, receipt); err != nil {
		t.Fatal(err)
	}
	paths := []string{manifest.LayoutPath, manifest.MetadataPath, filepath.Join(filepath.Dir(manifest.LayoutPath), "manifest.json"), filepath.Join(filepath.Dir(manifest.LayoutPath), "checksums.json"), filepath.Join(managed, "active.json")}
	before := make(map[string][]byte)
	for _, path := range paths {
		before[path], _ = os.ReadFile(path)
	}
	manager = libraryManager(t, managed, sources)
	if _, ready := manager.ValidatedSummary(); !ready {
		t.Fatal("legacy migration lost readiness")
	}
	upgraded, err := readValidationReceipt(managed, manifest)
	if err != nil || len(upgraded.FilesystemIDs) != len(manifest.Files) || !upgraded.Completed.Equal(receipt.Completed) {
		t.Fatalf("receipt migration: %#v %v", upgraded, err)
	}
	for _, path := range paths {
		after, _ := os.ReadFile(path)
		if !bytes.Equal(before[path], after) {
			t.Fatalf("migration modified immutable generation: %s", filepath.Base(path))
		}
	}
	// Simulate historical device numbers while preserving the enrolled map and
	// its original validation timestamp. Runtime opens must use the receipt too.
	manifest = historicalIdentityFixture(t, manifest, func(id *fat32virtual.Identity) { id.Device++ })
	upgraded.SourceIdentitySetHash = sourceIdentitySetHash(manifest)
	if err = persistValidationReceipt(managed, manifest, upgraded); err != nil {
		t.Fatal(err)
	}
	manager = libraryManager(t, managed, sources)
	if _, ready := manager.ValidatedSummary(); !ready {
		t.Fatal("enrolled legacy generation rejected device renumbering")
	}
	backend, err := OpenLibraryBackend(managed, manifest)
	if err != nil {
		t.Fatal(err)
	}
	if _, err = backend.ReadAt(make([]byte, 512), manifest.Files[0].VirtualOffset); err != nil {
		t.Fatal(err)
	}
	_ = backend.Close()
	// Removing enrollment must not turn a mismatched legacy device into trust.
	upgraded.FilesystemIDs = nil
	if err = persistValidationReceipt(managed, manifest, upgraded); err != nil {
		t.Fatal(err)
	}
	manager = libraryManager(t, managed, sources)
	if _, ready := manager.ValidatedSummary(); ready {
		t.Fatal("legacy device mismatch automatically enrolled")
	}
}
